config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions do
      resources :answers, only: [:create, :update]
  end

  devise_for :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  validates :body, presence: true, length: { minimum: 50 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers,  dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: 40 }
  validates :body, presence: true, length: { minimum: 150 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.question = @question

    if @answer.save
      flash[:notice] = 'Answer submitted'
      redirect_to question_path(params[:question_id])
    else
      flash[:notice] = 'Answer too short'
      redirect_to question_path(params[:question_id])
    end
  end

  def update
    @answers = Answer.where(question_id: params[:question_id])
    @answers.each do |a|
      if a.id == params[:id].to_i
        a.best = true
        a.update(id: params[:id])
        flash[:notice] = "Best answer set"
      else
        a.best = false
        a.update(id: a.id)
      end
    end
    binding.pry
    redirect_to question_path(params[:question_id])
  end

  protected
  def answer_params
    params.require(:answer).permit(:body, :question_id, :best)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def create
   @question = Question.new(question_params)
   if @question.save
     flash[:notice] = "Question asked"
     redirect_to '/'
   else
     flash[:error] = @question.errors.full_messages.join(". ")
     render :new
   end

  end
  def edit
    @question = Question.find(params[:id])
  end
  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      flash[:notice] = "Question is updated, i love you."
      redirect_to question_path
    else
      flash[:error] = @question.errors.full_messages.join(". ")
      render :edit
    end
  end
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = Answer.where(question_id: params[:id]).order(:best)
  end

  def destroy
    @question = Question.find(params[:id]).destroy
    flash[:notice] = "Question deleted"
      redirect_to '/questions'
  end

  protected
  def question_params
    params.require(:question).permit(:title, :body, :question_id)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Rescue Mission</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>
<%= form_for @question, url: question_path(@question), method: :patch do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit "save", class: "button" %>

<% end %>

app/views/questions/index.html.erb
<ul>
  <% @questions.each do |question| %>
  <li> <%=link_to question.title, question %> </li>
  <% end %>
</ul>
<%= link_to "New", new_question_path %>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit "submit", class: "button" %>

<% end %>

app/views/questions/show.html.erb
<h1> <%= @question.title %> </h1>
<p><%= @question.body %></p>
<%= link_to 'Delete', question_path(@question),
  method: :delete %>
  <%= link_to "Edit", edit_question_path %>

  <%= form_for [@question, @answer] do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body %>
    <%= f.submit "Submit", class: "button" %>
  <% end %>

<ul>
<% @answers.each do |answer| %>
  <li>
    <% if answer.best == false %>
    <%= "This is the best answer" %>
    <% end %>
  </li>
  <li><%= answer.body %></li>
  <li>
    <%= form_for [@question, answer] do |f| %>
    <%= f.submit "Best", class: "button" %>
    <% end %>
  </li>
<% end %>
</ul>